package Interfaz;

import javax.swing.*;

/**
 *
 * @author Stefania
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(650, 200, 150, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡Bienvenido a Hogwarts!");

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Descubre a qué casa perteneces, respondiendo el cuestionario del Sombrero seleccionador!");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/potter.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del alumno:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(88, 184, 163));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Comenzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(88, 184, 163));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(88, 184, 163));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Instrucciones");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//casilla para ingresar el nombre del jugador
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

//botón COMENZAR
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int toth = 0, totr = 0, totg = 0, tots = 0;
        String a, b, c, d, nom;
        String inicio = null;
        int[] puntosj1 = new int[4]; // arrays para puntos de jugador 1
        String[] jugadores = new String[1]; // arrays jugador 1 [0]
        nom = jTextField1.getText();
        do {
            for (int i = 0; i < 1; i++) { //recorre las posiciones del array 1 y 2.
                if (jTextField1.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del jugador para poder iniciar");
                } else {
                    switch (JOptionPane.showInputDialog(null, "1° Pregunta: ¿Qué es lo que más te molestaría que dijeran que sos?\nA - Egoísta\nB - Ignorante\nC - Cobarde\nD - Común")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Egoísta");
                            puntosj1[0] = toth += 1; //acumulador
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Ignorante");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Cobarde");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Común");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "2° Pregunta: Una vez cada siglo, el arbusto Flutterby produce flores que adaptan su aroma para atraer a los incautos. Si te atraía, olería a:\nA - Pergamino Fresco\nB - El mar\nC - Una Chimenea Crepitante\nD - Casa")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Pergamino Fresco");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "El Mar");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Una Chimenea Crepitante");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Casa");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "3° Pregunta: Preferirías inventar una poción que te garantice:\nA - Amor\nB - Sabiduría\nC - Gloria\nD - Poder")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Amor");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Sabiduría");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Gloria");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Poder");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "4° Pregunta: Después de que hayas muerto, ¿cómo te gustaría que reaccionen las personas cuando escuchen tu nombre?\nA - Que te extrañen con una sonrisa\nB - Que pienses en tus logros con admiración\nC - Que pidan escuchar más historias de tus aventuras\nD - Es más importante lo que piensan de mí mientras estoy vivo")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Te extrañen con una sonrisa");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Piensen en tus logros con admiración");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Pidan escuchar más historias de tus aventuras");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Es más importante lo que piensan de mí mientras estoy vivo.");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "5° Pregunta: ¿Qué instrumento te gusta más?\nA - Tambor\nB - Piano\nC - Trompeta\nD - Violín")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Tambor");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Piano");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Trompeta");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Violín");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "6° Pregunta: ¿Qué te resulta más difícil de aguantar?\nA - Hambre\nB - Soledad\nC - Aburrimiento\nD - Ser ignorado")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Hambre");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Soledad");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Aburrimiento");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Ser Ignorado");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "7° Pregunta: ¿Qué mascota elegirías llevar a Hogwarts?\nA - Sapo\nB - Búho\nC - Lechuza\nD - Gato negro")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Sapo");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Búho");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Lechuza");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Gato Negro");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "8° Pregunta: ¿Qué es lo que más deseas aprender en Hogwarts?\nA - Secretos sobre el castillo\nB - Aparición y Desaparición (materializarse y desmaterializarse a voluntad)\nC - Volar en escoba\nD - Maleficios y Hechizos")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Secretos sobre el castillo");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Aparición y Desaparicion (Materializarse y Desmaterializarse a voluntad)");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Volar en escoba");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Maleficios y Hechizos");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    switch (JOptionPane.showInputDialog(null, "9° Pregunta: ¿Cuál de las siguientes criaturas te gustaría estudiar más?\nA - Trolls\nB - Duendes\nC - Centauros\nD - Vampiros")) {
                        case "a":
                            //JOptionPane.showMessageDialog(null, "Trolls");
                            puntosj1[0] = toth += 1;
                            //System.out.println(puntosj1[0]);
                            break;
                        case "b":
                            //JOptionPane.showMessageDialog(null, "Duendes");
                            puntosj1[1] = totr += 1;
                            //System.out.println(puntosj1[1]);
                            break;
                        case "c":
                            //JOptionPane.showMessageDialog(null, "Centauros");
                            puntosj1[2] = totg += 1;
                            //System.out.println(puntosj1[2]);
                            break;
                        case "d":
                            //JOptionPane.showMessageDialog(null, "Vampiros");
                            puntosj1[3] = tots += 1;
                            //System.out.println(puntosj1[3]);
                            break;
                    }
                    //condiciones para determinar qué casa le toca al jugador1.
                    if ((toth > totr) && (toth > totg) && (toth > tots)) { //GANA HUFFLEPUFF
                        form2 f2= new form2();
                        f2.setVisible(true);
                        JOptionPane.showMessageDialog(null, nom + " ¡Perteneces a Hufflepuff!"); //muestra en la consola nombre del jugador 1
                    } else if ((totr > toth) && (totr > totg) && (totr > tots)) { //GANA RAVENCLAW
                        JOptionPane.showMessageDialog(null, nom + " ¡Perteneces a Ravenclaw!"); //muestra en la consola los nombres de los jugadores
                        form3 f3= new form3();
                        f3.setVisible(true);
                    } else if ((totg > toth) && (totg > totr) && (totg > tots)) { // GANA GRYFFINDOR
                        JOptionPane.showMessageDialog(null, nom + " ¡Perteneces a Gryffindor!"); //muestra en la consola los nombres de los jugadores
                        form4 f4= new form4();
                        f4.setVisible(true);
                    } else if ((tots > toth) && (tots > totr) && (tots > totg)) { // GANA SLYTHERIN
                        JOptionPane.showMessageDialog(null, nom + " ¡Perteneces a Slytherin!"); //muestra en la consola los nombres de los jugadores
                        form5 f5= new form5();
                        f5.setVisible(true);
                    }
                    inicio = JOptionPane.showInputDialog(null, "¿Comenzar un nuevo test?\n• Si\n• No");
                    System.out.println(puntosj1[0]); // = hufflepuff; //muestra en la consola cuantas respuestas A del jugador 1
                    System.out.println(puntosj1[1]); // = ravenclaw; //muestra en la consola cuantas respuestas B puntos del jugador 1
                    System.out.println(puntosj1[2]); // = gryffindor; //muestra en la consola cuantas respuestas C puntos del jugador 1
                    System.out.println(puntosj1[3]); // = slytherin; //muestra en la consola cuantas respuestas D puntos del jugador 1
                }//pregunta de nuevo para saber si vuelve a empezar o termino
            }
        } while (inicio.equalsIgnoreCase("si"));
    }//GEN-LAST:event_jButton1ActionPerformed
//botón SALIR
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
//propiedades de la ventana abierta
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_formWindowOpened
//botón INSTRUCCIONES
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null, "Responde 9 preguntas multiple choice.\nAl finalizar el test, sabrás a qué casa perteneces.\n¿Serás un amable Hufflepuff?, ¿Un sabio Ravenclaw?\n¿Tal vez un valiente Gryffindor? o ¿Un astuto Slytherin?");
    }//GEN-LAST:event_jButton3ActionPerformed

//GEN-FIRST:event_jTextField1ActionPerformed
 
//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
